### ISSUE TITLE
Remove hard-coding

### ISSUE THREAD

**Issue by dylanmcreynolds** [Xi-CAM/Xi-cam.CatalogViewer#2]
Currently, the viewer looks for a hard-coded key for grabbing images. 

This doesn't work for demoing on multiple beamlines. Need to come with a way to dynamically or by-configuration find the right image. This should be do-able with hints? @ronpandolfi

**Comment by danielballan** [comment]
As a first pass, I think it makes senses to look for any fields with the right dimensions. That's what we do.

**Comment by dylanmcreynolds** [comment]
This fixed in https://github.com/synchrotrons/Xi-cam.CatalogViewer/pulls
