### ISSUE TITLE
Question regarding logic for filtering image fields

### ISSUE THREAD

**Issue by birdzix** [Xi-CAM/Xi-cam.CatalogViewer#4]
from PR #3:
> One question we had was how to filter based on shape. We thought that at CHX, we'd seen an extra dimension, which we aren't sure how we'd deal with at this point.
For now, we have the logic:
if field_shape > 1 and field_shape < 5:

**Comment by birdzix** [comment]
See #6

**Comment by dylanmcreynolds** [comment]
This has been fixed with addition of field dropdown.
