### ISSUE TITLE
Need more information output when a non-image catalog is opened

### ISSUE THREAD

**Issue by birdzix** [Xi-CAM/Xi-cam.CatalogViewer#6]
Currently the CatalogViewer plugin will only open and display image type catalogs (by examing the shape of the fields in the catalog). If you try to open a non-image image type catalog, the viewport data does not change, and the run is logged. There is no message describing that this non-image type catalog will *not* be displayed.

It would be helpful to have a message saying that this run is not image data.

Regarding this, should CatalogViewer open *any* type of valid Catalog and display it? i.e. should CatalogViewer support displaying or inspecting any time of valid Catalog (and therefore show all fields in the combobox)?

**Comment by dylanmcreynolds** [comment]
The catalog viewer now only shows fields that are 2D. So this is no longer an issue.
